name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm run ci
    - run: npm run build
